# Generated by Django 2.2.7 on 2020-06-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MlModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=128)),
                ('price', models.FloatField(default=100)),
                ('content_duration', models.FloatField(default=20)),
                ('num_lectures', models.IntegerField(default=20)),
                ('level', models.CharField(choices=[('All Levels', 'All Levels'), ('Beginner Level', 'Beginner Level'), ('Intermediate Level', 'Intermediate Level'), ('Expert Level', 'Expert Level')], default='All Levels', max_length=32)),
                ('days', models.IntegerField(default=365)),
                ('prediction', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.SlugField(blank=True, max_length=256, unique=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MlModels.MlModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
